[{
  "history_id" : "3Dnuvb1Vsqm5",
  "history_input" : "# Write first python in Geoweaver\nimport os\nfrom datetime import datetime\n\nimport numpy as np\nfrom matplotlib import pyplot as plt\nfrom py_eddy_tracker import data\nfrom py_eddy_tracker.dataset.grid import RegularGridDataset",
  "history_output" : "Traceback (most recent call last):\n  File \"eddy_import.py\", line 7, in <module>\n    from py_eddy_tracker import data\nModuleNotFoundError: No module named 'py_eddy_tracker'\n",
  "history_begin_time" : 1663077130108,
  "history_end_time" : 1663077135874,
  "history_notes" : null,
  "history_process" : "6gs3ym",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "wulp5d73up2",
  "history_input" : "# Write first python in Geoweaver\nimport os\nfrom datetime import datetime\n\nimport numpy as np\nfrom matplotlib import pyplot as plt\nfrom py_eddy_tracker import data\nfrom py_eddy_tracker.dataset.grid import RegularGridDataset",
  "history_output" : "Traceback (most recent call last):\n  File \"eddy_import.py\", line 7, in <module>\n    from py_eddy_tracker import data\nModuleNotFoundError: No module named 'py_eddy_tracker'\n",
  "history_begin_time" : 1663076939089,
  "history_end_time" : 1663076948125,
  "history_notes" : null,
  "history_process" : "6gs3ym",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "d8tr1y3va7r",
  "history_input" : "# Write first python in Geoweaver\nimport os\nfrom datetime import datetime\n\nimport numpy as np\nfrom matplotlib import pyplot as plt\nfrom py_eddy_tracker import data\nfrom py_eddy_tracker.dataset.grid import RegularGridDataset",
  "history_output" : "Cannot run program \"python3.8\" (in directory \"C:\\Users\\user\\gw-workspace\\d8tr1y3va7r\"): CreateProcess error=2, The system cannot find the file specified",
  "history_begin_time" : 1663034965976,
  "history_end_time" : 1663034966591,
  "history_notes" : null,
  "history_process" : "6gs3ym",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "ymcdws1t66k",
  "history_input" : null,
  "history_output" : "Authentication Failed. Wrong Password.",
  "history_begin_time" : 1662472570631,
  "history_end_time" : 1662472577703,
  "history_notes" : null,
  "history_process" : "6gs3ym",
  "host_id" : "100001",
  "indicator" : "Failed"
},]
